/*
 * Copyright 2016-2025 Pavel Castornii.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.techsenger.toolkit.fx.table;

import javafx.collections.ListChangeListener.Change;
import javafx.collections.ObservableList;
import javafx.collections.transformation.TransformationList;

/**
 * This class allows to add one extra row to the end of the table. It can be used, when items are added
 * dynamically and it is necessary to have one total line in the table. But, using this list disables data ordering.
 * So, it won't be possible to order rows by clicking on column header. How to use - origin list is passed in
 * constructor and instance of LastRowObservableList is set as items to table view.
 *
 * @author Pavel Castornii
 */
public class LastRowObservableList<T> extends TransformationList<T, T> {

    private final T lastRow;

    public LastRowObservableList(ObservableList<? extends T> source, T lastRow) {
        super(source);
        this.lastRow = lastRow;
    }

    @Override
    protected void sourceChanged(Change<? extends T> c) {
        // no need to modify change:
        // indexes generated by the source list will match indexes in this list
        fireChange(c);
    }

    @Override
    public int getSourceIndex(int index) {
        if (index < getSource().size()) {
            return index;
        }
        return -1;
    }

    @Override
    public int getViewIndex(int index) {
        return index;
    }

    @Override
    public T get(int index) {
        if (index < getSource().size()) {
            return getSource().get(index);
        } else if (index == getSource().size()) {
            return lastRow;
        } else {
            throw new ArrayIndexOutOfBoundsException(index);
        }
    }

    @Override
    public int size() {
        return getSource().size() + 1;
    }

}
