<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.techsenger.toolkit</groupId>
        <artifactId>toolkit</artifactId>
        <version>1.1.0</version>
    </parent>

    <groupId>com.techsenger.toolkit</groupId>
    <artifactId>toolkit-rmi</artifactId>
    <packaging>jar</packaging>
    <name>Toolkit - RMI</name>
    <description>Classes for working with RMI</description>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
    </dependencies>
</project>






